pipeline {
    agent any
    environment {
        GITHUB_CREDENTIALS = credentials('github-credentials')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: "${GITHUB_CREDENTIALS}",
                    url: 'https://github.com/alx-backend-python/messaging_app.git'
            }
        }
        stage('Install Dependencies & Run Tests') {
            steps {
                sh '''
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  pytest --maxfail=1 --disable-warnings -q --junitxml=report.xml
                '''
            }
            post { always { junit 'report.xml' } }
        }
        stage('Build Docker Image') {
            environment {
                DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
            }
            steps {
                sh '''
                  docker build -t ${DOCKER_HUB_CREDENTIALS_USR}/messaging_app:latest .
                  echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin
                  docker push ${DOCKER_HUB_CREDENTIALS_USR}/messaging_app:latest
                '''
            }
        }
    }
}
